In [15]:
import scipy
import numpy as np
from scipy.special import comb,perm
#from sympy import *
import itertools 

In [6]:
k = 2
a = 'abab'
b = 'ababab'
c = []
c[0] = k
c[1] = a
c[2] = b

IndexError: list assignment index out of range

In [ ]:
a = input()
i = a.find(' ')
a = [int(a[:i]),int(a[i+1:])]
print(a)

In [26]:
import numpy as np
import itertools
N = input()
p = input()
M = input()

def  miHomeGiftBag(p, M):
    
    #p = input()
    p = [int(i) for i in p.split()]
    M = int(M)
    for i in range(1,len(p)+1):
        c = np.array(list(itertools.combinations(p,i)))
        c_sum = np.sum(c,1)
        if M in c_sum:
            return 1
            
        #if i == len(p):
    return 0
res = miHomeGiftBag(p, M)
print(res)


6
99 199 1999 10000 39 1499
10238
1


In [ ]:
import numpy as np
import itertools
#N = input()
p = input()
M = input()

def  miHomeGiftBag(p, M):
    
    #p = input()
    p = [int(i) for i in p.split()]
    M = [int(i) for i in M.split()]
    for i in range(1,len(p)+1):
        c = np.array(list(itertools.combinations(p,i)))
        c_sum = np.sum(c,1)
        if M in c_sum:
            return 1
            
        #if i == len(p):
    return 0
res = miHomeGiftBag(p, M)
print(res)


In [78]:
#5个数分成3组，所有组和中的最大值为所有组的结果，求结果最小为多少
a = [5,3]#输入，5个数，3组
b = [1,4,2,3,5]#具体的数
#贪心发把最大数逐个给和最小的组
#a = [1,2,5,4]
b.sort(reverse=True)
print(b)
m = a[0]//a[1] + 1
#rr = np.random.rand(a[1],1)#可以使用随机数代替0，最后减去初始值
rr = np.zeros([a[1],1])
r = rr.copy()
print(r)
for i in b:
    #print(np.min(r))
    #c_i = np.where(r==np.min(r,axis=0))
    c_i = np.argmin(r)#please use this function
    print(c_i)
    r[c_i]=r[c_i]+i
    #b.pop(b.index(max(b)))
    #print(i)
    #print(r[c_i])

print(rr)
r = r - rr   
print(a)
print(b)
print(r)

[5, 4, 3, 2, 1]
[[ 0.]
 [ 0.]
 [ 0.]]
0
1
2
2
1
[[ 0.]
 [ 0.]
 [ 0.]]
[5, 3]
[5, 4, 3, 2, 1]
[[ 5.]
 [ 5.]
 [ 5.]]


In [20]:
p = '99 199 1999 10000 39 1499'
p = [int(i) for i in p.split()]
M = 10238
for i in range(1,len(p)+1):
    c = np.array(list(itertools.combinations(p,i)))
    c_sum = np.sum(c,1)
    if M in c_sum:
        print(1)
        break
    if i == len(p):
        print(0)


#print(p)

1


In [1]:
a = [7 14 8]
a,b,c = (int(x) for x in raw_input().split())
n = (np.sqrt(1+8*sum(a))-1)*0.5
if a[1]<n:
    print(1)
else:
    N = np.arange(1,n+1,dtype=int)
    for i in N[1:]:
        c = np.array(list(itertools.combinations(N,i)))
        
        c_sum = np.sum(c,1)
        #print(c_sum)
        if a[0] in c_sum:
            print(i)
            break
        else:
            print(-1)



SyntaxError: invalid syntax (<ipython-input-1-a3b2b101d669>, line 1)

In [51]:
print(a)

['7', '14']


In [42]:
N = np.arange(1,n+1)
cc = np.array(list(itertools.combinations(N,5)))
print(cc)
print(np.sum(cc,1))

[[ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  6.]
 [ 1.  2.  3.  5.  6.]
 [ 1.  2.  4.  5.  6.]
 [ 1.  3.  4.  5.  6.]
 [ 2.  3.  4.  5.  6.]]
[ 15.  16.  17.  18.  19.  20.]


In [9]:
#Scrip的使用，提供了真正的矩阵运算
#求解线性方程组2x1-x2^2=1,x1^2-x2=2
from scipy.optimize import fsolve #导入求解方程组的函数
def f(x): #定义要求解的方程组
    x1 = x[0]
    x2 = x[1]
    return [2*x1 - x2**2 - 1, x1**2 -x2 -2]
result = fsolve(f,[1,1]) #出入初值[1,1]并求解
print(result) #输出结果

[ 1.91963957  1.68501606]


In [32]:
data = np.random.rand(3,3)
data =np.array([[0,0,10],[60,0,10],[30,30,10]])
#f=[0,0,0]
def f(x1,data):
    x = x1[0]
    y = x1[1]
    k = x1[2]
    
   
        #fun[i]= [(x-data[i,0])**2 + (y-data[i,1])**2 - k*data[i,2]**2]
    return [(x-data[0,0])**2 + (y-data[0,1])**2 - k*data[0,2]**2,
            (x-data[1,0])**2 + (y-data[1,1])**2 - k*data[1,2]**2,
            (x-data[2,0])**2 + (y-data[2,1])**2 - k*data[2,2]**2]
result = fsolve(f,[0,0,0],args=data)
print('%.6f %0.6f'%(result[0],result[1]))

30.000000 -0.000000


In [33]:
from scipy.optimize import fsolve
import numpy as np
def input_data(data):
    data = np.array(data)
    result = fsolve(f,[0,0,0],args=data)
    print('%.6f %0.6f'%(result[0],result[1]))

def f(x1,data):
    x = x1[0]
    y = x1[1]
    k = x1[2]
    
   
        #fun[i]= [(x-data[i,0])**2 + (y-data[i,1])**2 - k*data[i,2]**2]
    return [(x-data[0,0])**2 + (y-data[0,1])**2 - k*data[0,2]**2,
            (x-data[1,0])**2 + (y-data[1,1])**2 - k*data[1,2]**2,
            (x-data[2,0])**2 + (y-data[2,1])**2 - k*data[2,2]**2]

In [54]:
data = [[2,0],[5,7],[1,3],[1,5],[2,3],[2,5],[3,4],[4,5],[3,5],[4,3],[1,2],[2,3],[3,4]]

def splitclass(data):
    data = np.array(data)
    n = []
    #s = 0
    e = 1
    datas = []
    for i in range(data[0,0]):
        s = e 
        e = s + data[s,1] + 1
        datas.append(data[s:e])
    return datas
datas = splitclass(data)
print( len(datas))
print(datas[0])
for i in range(len(datas)):
    data = datas[i]
    a = np.arange(1,data[0,0]+1)
    for i in range(data[0,1]):
        if a[0] in data[i+1]:
            data
            b.apend()
        
    

2
[[5 7]
 [1 3]
 [1 5]
 [2 3]
 [2 5]
 [3 4]
 [4 5]
 [3 5]]


In [69]:
2 in [2,3]
a = np.arange(1,6)
a = list(a)
b = a.pop(1)
print(a)
#b.append(3)
print(b)
a.append(100)
print(a)

[1, 3, 4, 5]
2
[1, 3, 4, 5, 100]


In [ ]:
def judge(data):
    for i in range(data[0,0]):
        

In [72]:
a = np.random.rand(10,2)
for i,j in a:
    print(i,j)
    print('w')

0.668057325611 0.56799240131
w
0.0383186661205 0.829029149515
w
0.541670784313 0.797901501893
w
0.246300836135 0.98158773176
w
0.0850824364108 0.807476837156
w
0.255292272637 0.680005552966
w
0.0831679294906 0.642507580536
w
0.296004273918 0.30395171281
w
0.654628272281 0.234785020907
w
0.493545405868 0.979920271549
w


In [5]:
#若一序列进栈顺序为a1,a2,a3,a4，问存在多少种可能的出栈序列（ ）
#n个数的计算公式Comb(2n,n)/(n+1)
n = 4
comb(2*n,n)/(n+1)

14.0

In [3]:
    def removeDuplicates( nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        new_nums = []
        for i in nums:
            if i not in new_nums:
                new_nums.append(i)
        nums = new_nums
        return len(nums)
nums = [1,1,2]
removeDuplicates([1,1,2])
nums[:2]

[1, 1]

In [21]:
a =[1,2,3]
b = [2,3,2]
set(a) & set(b)

{2, 3}

In [22]:
a = 123
b = str(a)
c = int(b)
c

123

In [2]:
10*9*8*7/(10*10*10*10)


0.504

In [4]:
0.6*0.5 + 0.4*(2/6)


0.43333333333333335

In [7]:
13/79

0.16455696202531644

In [ ]:
class Solution(object):
    def isHappy(self, n):
        """
        :type n: int
        :rtype: bool
        """
        num = n
        
        while 1 :
            ans = []
            s = str(abs(num))
            for i in s:
                ans.append(int(i)**2)
            num = sum(ans)
            if num == 1:
                return True

In [37]:
a = bin(1)
b = bin(4)
b.count('1')
print(len(a))
print(b.find('b'))
print(a)
print(b)
ans = 0
for i,j in zip(a,b):
    if i != j:
        ans+=1
ans
b.count('1')

3
1
0b1
0b100


1

In [45]:

def hammingWeight(self, n):
        """
        :type n: int
        :rtype: int
        """
        bn = format(n, 'b').zfill(32)
        return bn.count('1')

b = format(3,'b')

In [46]:
help(b.zfill)

Help on built-in function zfill:

zfill(...) method of builtins.str instance
    S.zfill(width) -> str
    
    Pad a numeric string S with zeros on the left, to fill a field
    of the specified width. The string S is never truncated.



Find the contiguous subarray within an array (containing at least one number) which has the largest sum. 
For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6. 

In [15]:
class Solution:
    # @param A, a list of integers
    # @return an integer
    # 6:57
    def maxSubArray(self, A):
        if not A:
            return 0

        curSum = maxSum = A[0]
        for num in A[1:]:
            curSum = max(num, curSum + num)
            print(curSum,end='')
            maxSum = max(maxSum, curSum)
            print(maxSum)

        return maxSum
        
Solution().maxSubArray([-2,1,-3,4,-1,2,1,-5,4])

11
-21
44
34
55
66
16
56


6

In [11]:
a = np.array([-2,1,-3,4,-1,2,1,-5,4])
a.max()


array([False, False, False,  True, False, False, False, False,  True], dtype=bool)

In [16]:
class Solution(object):
    def moveZeroes(self, nums):
        """
        :type nums: List[int]
        :rtype: void Do not return anything, modify nums in-place instead.
        """
        #self.nums = nums
        ans,ans2 = [],[]
        n = len(nums)
        for i in range(n):
            if nums[i] != 0:
                ans.append(nums[i])
            else:
                ans2.append(nums[i])
            if i == n-1:
                nums = ans + ans2 #局域变量
nums = [0,1,2,0,6]
Solution().moveZeroes(nums)                
nums

[0, 1, 2, 0, 6]

In [17]:
class Solution(object):
    def moveZeroes(self, nums):
        """
        :type nums: List[int]
        :rtype: void Do not return anything, modify nums in-place instead.
        """
        #self.nums = nums
        ans,ans2 = [],[]
        n = len(nums)
        for i in range(n):
            if nums[i] != 0:
                ans.append(nums[i])
            else:
                ans2.append(nums[i])
            if i == n-1:
                nums[:] = ans + ans2 #全局变量
nums = [0,1,2,0,6]
Solution().moveZeroes(nums)                
nums

[1, 2, 6, 0, 0]

In [10]:
np.add(1,2)
a=1
b=2
c=[1,2]
#sum(c)
d = [3,2]
c = d
c

[3, 2]

In [15]:
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        self.nums = nums
        self.target = target
        n = len(nums)
        for i in range(n):
            for j in range(i+1,n):
                if self.nums[i] + self.nums[j] == self.target:
                    return [i,j]
Solution().twoSum([3,2,4],6)

[1, 2]

In [5]:
a = [1,2,3,4]
b = [4,5,6,7]
a.length
for i,j in zip(a,b):
    mysum = i+j
    print(mysum)

AttributeError: 'list' object has no attribute 'length'

In [38]:
class Solution(object):
    def addTwoNumbers(self, l1, l2):
        """
        :type l1: ListNode
        :type l2: ListNode
        :rtype: ListNode
        """
        power = 0;
        #n = len(l1)
        result = 0
        for i,j in zip(l1,l2):
            mysum = i + j
            power+=1
            print(power)
            if mysum >= 10:
                result+= (mysum//10)*(10**power)
                result+= (mysum%10)*10**(power-1)
            else:
                result+= mysum*10**(power-1)
            print(result)
        return result
Solution().addTwoNumbers([2,4,3],[5,6,4])

1
7
2
107
3
807


807

In [49]:
# Definition for singly-linked list.
class ListNode(object):
        def __init__(self, x):
            self.val = x
            self.next = None

class Solution(object):
    def addTwoNumbers(self, l1, l2):
        """
        :type l1: ListNode
        :type l2: ListNode
        :rtype: ListNode
        """
x = [1,2,3]
x
b = ListNode(x)
print(x)

AttributeError: 'list' object has no attribute 'length'

In [62]:
a = [1,2,3,4,5,6,7,]
i = 1
a[0:i]+a[i+1:]

[1, 3, 4, 5, 6, 7]

In [64]:
nums = [1,1,2,2,3]
set(nums)
help(set)

Help on class set in module builtins:

class set(object)
 |  set() -> new empty set object
 |  set(iterable) -> new set object
 |  
 |  Build an unordered collection of unique elements.
 |  
 |  Methods defined here:
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iand__(self, value, /)
 |      Return self&=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __ior__(self, value, /)
 |      Return self|=value.
 |  
 |  __isub__(self, value, /)
 |      Return self-=value.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __ixor__(self, value, /)
 |      Re

In [47]:

class Solution(object):
    def fizzBuzz(self, n):
        """
        :type n: int
        :rtype: List[str]
        """
        ans = []
        for i in range(1,n+1):
            if i%3==0 and i%5==0:
                ans.append('FizzBuzz')
            elif i%3==0:
                 ans.append('Fizz')
            elif i%5==0:
                 ans.append('Buzz') 
            else:
                 ans.append(str(i))
        return ans
Solution().fizzBuzz(4)

['1', '2', 'Fizz', '4']

In [31]:
a=10200
b = str(a)
int(b[-1::-1])

201

In [36]:
2**31-1


2147483647

In [37]:
dir(scipy.add)



['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

NameError: name 'source' is not defined

In [22]:
class Mycalculater():
    '''计算器'''
    def __init__(self, number1, number2):
        """初始化属性name和age"""
        self.number1 = number1
        self.number2 = number2
        
    def plus(self,):
        
        return self.number1 + self.number2
    def minus(self,):
        return self.number1 - self.number2
    
        
    

In [24]:
Mycalculater(2,3).plus()
Mycalculater(2,3).minus()

-1